# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoFactura',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('solenium', 'solenium'), ('inversionista', 'inversionista')], max_length=13)),
                ('fecha', models.CharField(max_length=7)),
                ('inversionista', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('enlace_soporte', models.CharField(blank=True, max_length=1000, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_factura_por_contrato_id', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'contrato_factura',
            },
        ),
        migrations.CreateModel(
            name='FacturaAgrupacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_sic_contrato', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'factura_agrupacion',
                'unique_together': {('codigo_sic_contrato',)},
            },
        ),
        migrations.CreateModel(
            name='FacturaEmitida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=7)),
                ('numero_factura', models.CharField(blank=True, max_length=80, null=True)),
                ('emitida_por', models.CharField(blank=True, max_length=120, null=True)),
                ('emitida_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'factura_emitida',
                'unique_together': {('nombre', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='FacturaOrden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'factura_orden',
                'unique_together': {('nombre',)},
            },
        ),
    ]
