# Generated by Django 6.0.8 on 2026-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaagrupacion',
            name='codigo_sic_contrato',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
