# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_frontera', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_frontera', models.CharField(max_length=255)),
                ('tipo_frontera', models.CharField(choices=[('generacion', 'generacion'), ('consumo', 'consumo'), ('generacion_consumo', 'generacion_consumo'), ('consumo_auxiliar', 'consumo_auxiliar'), ('consumo_propio', 'consumo_propio')], max_length=18)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('en_registro', 'en_registro'), ('cancelada', 'cancelada'), ('en_falla', 'en_falla')], default='en_registro', max_length=11)),
                ('fecha_registro_asic', models.DateField(blank=True, null=True)),
                ('tipo_punto_medicion', models.IntegerField(blank=True, null=True)),
                ('nivel_tension_kv', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('clase_ct', models.CharField(blank=True, choices=[('0.2', '0.2'), ('0.2s', '0.2s'), ('0.5s', '0.5s')], max_length=4, null=True)),
                ('clase_pt', models.CharField(blank=True, choices=[('0.2', '0.2'), ('0.5', '0.5')], max_length=3, null=True)),
                ('nivel_tension', models.IntegerField(blank=True, null=True)),
                ('transferencia_maxima_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('fecha_inicio_representacion', models.DateField(blank=True, null=True)),
                ('agente_exportador', models.CharField(blank=True, max_length=255, null=True)),
                ('agente_importador', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sic_submercado_exportador', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_sic_submercado_consumo', models.CharField(blank=True, max_length=20, null=True)),
                ('nro_serie_med_ppal', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_med_ppal', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_med_ppal', models.CharField(blank=True, max_length=100, null=True)),
                ('clase_medidor', models.CharField(blank=True, choices=[('0.2s', '0.2s'), ('0.5s', '0.5s')], max_length=4, null=True)),
                ('num_elementos_med_ppal', models.IntegerField(blank=True, null=True)),
                ('fecha_cambio_med_ppal', models.DateField(blank=True, null=True)),
                ('entidad_calibradora_med_ppal', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_calibracion_med_ppal', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_ppal', models.DateField(blank=True, null=True)),
                ('nro_serie_med_resp', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_med_resp', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_med_resp', models.CharField(blank=True, max_length=100, null=True)),
                ('num_elementos_med_resp', models.IntegerField(blank=True, null=True)),
                ('fecha_cambio_med_resp', models.DateField(blank=True, null=True)),
                ('entidad_calibradora_med_resp', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_calibracion_med_resp', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_resp', models.DateField(blank=True, null=True)),
                ('quoia_border_id', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fronteras',
            },
        ),
        migrations.CreateModel(
            name='FronteraQuoiaIgnorada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frt_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fronteras_quoia_ignoradas',
            },
        ),
        migrations.CreateModel(
            name='OperadorRed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_legal', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'operadores_red',
            },
        ),
        migrations.CreateModel(
            name='OperadorRedContacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'operadores_red_contactos',
            },
        ),
        migrations.CreateModel(
            name='ContratoFrontera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contrato_servicio', models.ForeignKey(db_column='contrato_servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_frontera_por_contrato_servicio_id', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'contrato_frontera',
            },
        ),
    ]
