# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fronteras', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontera',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fronteras', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='contratofrontera',
            name='frontera',
            field=models.ForeignKey(db_column='frontera_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_frontera_por_frontera_id', to='fronteras.frontera'),
        ),
        migrations.AddField(
            model_name='fronteraquoiaignorada',
            name='ignorado_por_usuario',
            field=models.ForeignKey(blank=True, db_column='ignorado_por_usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fronteras_quoia_ignoradas_por_ignorado_por_usuario_id', to='plataforma.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='operadorred',
            unique_together={('nombre_legal',)},
        ),
        migrations.AddField(
            model_name='frontera',
            name='operador_red',
            field=models.ForeignKey(blank=True, db_column='operador_red_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fronteras_por_operador_red_id', to='fronteras.operadorred'),
        ),
        migrations.AddField(
            model_name='operadorredcontacto',
            name='operador_red',
            field=models.ForeignKey(db_column='operador_red_id', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='fronteras.operadorred'),
        ),
        migrations.AlterUniqueTogether(
            name='contratofrontera',
            unique_together={('contrato_servicio', 'frontera')},
        ),
        migrations.AlterUniqueTogether(
            name='fronteraquoiaignorada',
            unique_together={('frt_code',)},
        ),
    ]
