# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasFuenteIngreso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('columna_origen', models.CharField(max_length=40)),
                ('etiqueta', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alias_fuente_ingreso',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionLiquidacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(default='normal', max_length=10)),
            ],
            options={
                'db_table': 'clasificacion_liquidacion',
            },
        ),
        migrations.CreateModel(
            name='MapeoCeldaConcepto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('hoja', models.CharField(max_length=120)),
                ('celda', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mapeo_celda_concepto',
            },
        ),
        migrations.CreateModel(
            name='PanelConsecutivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=20)),
                ('inversionista_nombre', models.CharField(max_length=255)),
                ('consecutivo_ingresos', models.IntegerField(blank=True, null=True)),
                ('consecutivo_costos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'panel_consecutivo',
            },
        ),
        migrations.CreateModel(
            name='PanelContable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(default='preliquidacion', max_length=20)),
                ('liquidar', models.BooleanField(default=True)),
                ('liquidar_ingresos', models.BooleanField(default=True)),
                ('liquidar_costos', models.BooleanField(default=True)),
                ('generar_mandatos', models.BooleanField(default=False)),
                ('tiene_bolsa', models.BooleanField(default=False)),
                ('tiene_costos', models.BooleanField(default=False)),
                ('ingreso_bruto_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('comercializador', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('consecutivo_ingresos', models.IntegerField(blank=True, null=True)),
                ('consecutivo_costos', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(default='er', max_length=10)),
                ('er_filename', models.CharField(blank=True, max_length=300, null=True)),
                ('er_snapshot', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'panel_contable',
            },
        ),
        migrations.CreateModel(
            name='PanelContableLinea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inversionista_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('grupo', models.CharField(max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('valor_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('comprobante_contable', models.CharField(blank=True, max_length=120, null=True)),
                ('hoja', models.CharField(blank=True, max_length=120, null=True)),
                ('celda', models.CharField(blank=True, max_length=20, null=True)),
                ('fuente', models.CharField(blank=True, max_length=20, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'panel_contable_linea',
            },
        ),
        migrations.CreateModel(
            name='PanelSoporte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('archivo_url', models.CharField(max_length=1000)),
                ('archivo_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'panel_soporte',
            },
        ),
    ]
