# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasfuenteingreso',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='alias_fuente_ingreso_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='clasificacionliquidacion',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_liquidacion_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='mapeoceldaconcepto',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='mapeo_celda_concepto_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='panelconsecutivo',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='panel_consecutivo_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='panelconsecutivo',
            name='proyecto_inversionista',
            field=models.ForeignKey(blank=True, db_column='proyecto_inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_consecutivo_por_proyecto_inversionista_id', to='proyectos.proyectoinversionista'),
        ),
        migrations.AddField(
            model_name='panelcontable',
            name='generado_por',
            field=models.ForeignKey(blank=True, db_column='generado_por_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='panel_contable_por_generado_por_id', to='plataforma.usuario'),
        ),
        migrations.AddField(
            model_name='panelcontable',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='panel_contable_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='panelcontablelinea',
            name='panel',
            field=models.ForeignKey(db_column='panel_id', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.panelcontable'),
        ),
        migrations.AddField(
            model_name='panelcontablelinea',
            name='proyecto_inversionista',
            field=models.ForeignKey(blank=True, db_column='proyecto_inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_contable_linea_por_proyecto_inversionista_id', to='proyectos.proyectoinversionista'),
        ),
        migrations.AddField(
            model_name='panelsoporte',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='panel_soporte_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='aliasfuenteingreso',
            unique_together={('columna_origen', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionliquidacion',
            unique_together={('periodo', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='mapeoceldaconcepto',
            unique_together={('concepto', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='panelconsecutivo',
            unique_together={('inversionista_nombre', 'periodo', 'proyecto', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='panelcontable',
            unique_together={('periodo', 'proyecto', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='panelsoporte',
            unique_together={('concepto', 'grupo', 'periodo', 'proyecto', 'tipo')},
        ),
    ]
