# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidaciones', '0001_initial'),
        ('ppa', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsicSolicitud',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requerimiento_asic', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_solicitud', models.CharField(choices=[('registro', 'registro'), ('modificacion', 'modificacion'), ('terminacion', 'terminacion'), ('desistimiento', 'desistimiento')], max_length=13)),
                ('prioridad_limitacion', models.IntegerField(blank=True, null=True)),
                ('codigo_sic_contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_sic_vendedor', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_sic_comprador', models.CharField(blank=True, max_length=10, null=True)),
                ('cedula_agente_vendedor', models.CharField(blank=True, max_length=30, null=True)),
                ('cedula_agente_comprador', models.CharField(blank=True, max_length=30, null=True)),
                ('contrato_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_mercado', models.CharField(blank=True, default='No regulado', max_length=50, null=True)),
                ('tipo_asignacion', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_fncer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_despacho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado_solicitud', models.CharField(choices=[('en_proceso', 'en_proceso'), ('publicado', 'publicado'), ('rechazado', 'rechazado'), ('desistido', 'desistido'), ('terminado', 'terminado')], default='en_proceso', max_length=10)),
                ('nombre_interno', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('link_archivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('reemplaza_anterior', models.BooleanField(default=True)),
                ('es_duplicado', models.BooleanField(default=False)),
                ('uso_del_recurso', models.BooleanField(default=False)),
                ('modalidad_pago', models.CharField(blank=True, max_length=3, null=True)),
                ('fecha_envio_xm', models.DateField(blank=True, null=True)),
                ('fecha_respuesta_xm', models.DateField(blank=True, null=True)),
                ('numero_radicado', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato_ppa', models.ForeignKey(blank=True, db_column='contrato_ppa_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asic_solicitudes_por_contrato_ppa_id', to='ppa.ppacontrato')),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asic_solicitudes_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'asic_solicitudes',
            },
        ),
        migrations.CreateModel(
            name='AsicCambioContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_sic_contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('contrato_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_frt_original', models.CharField(blank=True, max_length=20, null=True)),
                ('energia_mensual_mwh_original', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('codigo_frt_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('energia_mensual_mwh_nuevo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto_nuevo', models.ForeignKey(blank=True, db_column='proyecto_nuevo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asic_cambios_contratos_por_proyecto_nuevo_id', to='proyectos.proyecto')),
                ('proyecto_original', models.ForeignKey(blank=True, db_column='proyecto_original_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asic_cambios_contratos_por_proyecto_original_id', to='proyectos.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, db_column='solicitud_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asic_cambios_contratos_por_solicitud_id', to='mercado_xm.asicsolicitud')),
            ],
            options={
                'db_table': 'asic_cambios_contratos',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionEnergiaMensual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('categoria', models.CharField(max_length=32)),
                ('codigo_sic', models.CharField(blank=True, max_length=32, null=True)),
                ('uso_del_recurso', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('calculado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato_ppa', models.ForeignKey(blank=True, db_column='contrato_ppa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificacion_energia_mensual_por_contrato_ppa_id', to='ppa.ppacontrato')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_energia_mensual_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'clasificacion_energia_mensual',
            },
        ),
        migrations.CreateModel(
            name='DespachoContratoDia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('codigo_sic_contrato', models.CharField(db_index=True, max_length=40)),
                ('fecha', models.DateField()),
                ('kwh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'despacho_contrato_dia',
                'unique_together': {('codigo_sic_contrato', 'fecha', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DespachoContratoMensual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('codigo_sic_contrato', models.CharField(max_length=40)),
                ('vendedor', models.CharField(blank=True, max_length=40, null=True)),
                ('comprador', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('kwh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('fecha_min', models.DateField(blank=True, null=True)),
                ('fecha_max', models.DateField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'despacho_contrato_mensual',
                'unique_together': {('codigo_sic_contrato', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='GesconDiccionarioContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_contrato', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'gescon_diccionario_contratos',
                'unique_together': {('codigo_contrato',)},
            },
        ),
        migrations.CreateModel(
            name='PrecioBolsaMensual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'precio_bolsa_mensual',
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='RecProceso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_proceso', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('en_preparacion', 'en_preparacion'), ('radicado', 'radicado'), ('en_revision', 'en_revision'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='en_preparacion', max_length=14)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('cantidad_energia_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('titular_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('titular_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('relacion_propietario', models.CharField(blank=True, choices=[('propietario', 'propietario'), ('comprador_ppa', 'comprador_ppa'), ('tercero', 'tercero')], max_length=13, null=True)),
                ('tecnologia_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente_datos', models.CharField(blank=True, choices=[('asic', 'asic'), ('medidor', 'medidor'), ('plataforma_monitoreo', 'plataforma_monitoreo'), ('otro', 'otro')], max_length=20, null=True)),
                ('ente_certificador', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_radicado', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_ente', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec_procesos_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'rec_procesos',
            },
        ),
        migrations.CreateModel(
            name='CumplimientoMensual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('gen_total_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('compromiso_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('compras_bolsa_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('excedentes_bolsa_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('precio_bolsa_promedio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('compras_bolsa_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('excedentes_bolsa_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('cerrado', 'cerrado'), ('facturado', 'facturado')], default='pendiente', max_length=9)),
                ('tarifa_ppa_cop_mwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valoracion_contrato_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contrato_ppa', models.ForeignKey(db_column='contrato_ppa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cumplimiento_mensual_por_contrato_ppa_id', to='ppa.ppacontrato')),
                ('liquidacion', models.ForeignKey(blank=True, db_column='liquidacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimiento_mensual_por_liquidacion_id', to='liquidaciones.liquidacion')),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimiento_mensual_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'cumplimiento_mensual',
                'unique_together': {('anio', 'contrato_ppa', 'mes')},
            },
        ),
    ]
