# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaAjuste',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('semanal', 'semanal'), ('txr', 'txr'), ('mensual', 'mensual')], max_length=7)),
                ('fecha', models.DateField(db_index=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('restricciones', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stn', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('trm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ptb', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_ungc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_ungg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_consignar', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('disponible_custodia', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('congelado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_ajuste_txr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'garantias_ajustes',
            },
        ),
        migrations.CreateModel(
            name='GarantiaSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField(db_index=True)),
                ('clave', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('neto_mwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('precio_bolsa', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_energia', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_plantas_nuevas', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_regulatorio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('garantia_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('plantas_nuevas', models.IntegerField(default=0)),
                ('kwh_planta_nueva', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('regulatorio_anio', models.IntegerField(blank=True, null=True)),
                ('regulatorio_mes', models.IntegerField(blank=True, null=True)),
                ('regulatorio_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'garantia_snapshot',
            },
        ),
        migrations.CreateModel(
            name='BalcttosNeto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia_corte', models.IntegerField(default=0)),
                ('neto_mwh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'balcttos_neto',
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='GarantiaPagado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'garantia_pagado',
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='GarCalculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agente', models.CharField(max_length=10)),
                ('esquema', models.CharField(max_length=10)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('fecha_calculo', models.DateField(blank=True, null=True)),
                ('periodo_ini', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('etiqueta_periodo', models.CharField(blank=True, max_length=40, null=True)),
                ('base_30d_ini', models.DateField(blank=True, null=True)),
                ('base_30d_fin', models.DateField(blank=True, null=True)),
                ('base_sem_ini', models.DateField(blank=True, null=True)),
                ('base_sem_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gar_calculo',
                'unique_together': {('agente', 'esquema', 'fecha_vencimiento', 'periodo_fin', 'periodo_ini')},
            },
        ),
        migrations.CreateModel(
            name='XmArchivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_index=True, max_length=30)),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('periodo_ini', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('disponible_desde', models.DateTimeField()),
                ('origen_disponibilidad', models.CharField(max_length=12)),
                ('sha256', models.CharField(max_length=64)),
                ('bytes_len', models.IntegerField(default=0)),
                ('filas_ingeridas', models.IntegerField(default=0)),
                ('esquema_ok', models.BooleanField(default=True)),
                ('esquema_detalle', models.JSONField(blank=True, null=True)),
                ('ingerido_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'xm_archivo',
                'unique_together': {('sha256',)},
            },
        ),
        migrations.CreateModel(
            name='GarComponentePred',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=80)),
                ('horizonte_dias', models.IntegerField()),
                ('cuantil', models.DecimalField(decimal_places=3, max_digits=4)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=22)),
                ('modelo_version', models.CharField(max_length=40)),
                ('calculado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculo', models.ForeignKey(db_column='calculo_id', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='garantias.garcalculo')),
            ],
            options={
                'db_table': 'gar_componente_pred',
                'unique_together': {('calculo', 'componente', 'cuantil', 'horizonte_dias', 'modelo_version')},
            },
        ),
        migrations.CreateModel(
            name='GarComponenteReal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=22)),
                ('calculo', models.ForeignKey(db_column='calculo_id', on_delete=django.db.models.deletion.CASCADE, related_name='reales', to='garantias.garcalculo')),
            ],
            options={
                'db_table': 'gar_componente_real',
                'unique_together': {('calculo', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='XmMedida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_documento', models.DateField()),
                ('hora', models.IntegerField(default=0)),
                ('entidad', models.CharField(max_length=60)),
                ('concepto', models.CharField(max_length=120)),
                ('concepto_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=22)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('archivo', models.ForeignKey(db_column='archivo_id', on_delete=django.db.models.deletion.PROTECT, related_name='xm_medida_por_archivo_id', to='garantias.xmarchivo')),
            ],
            options={
                'db_table': 'xm_medida',
                'unique_together': {('concepto', 'entidad', 'fecha_documento', 'hora', 'tipo', 'version')},
            },
        ),
    ]
