from fastapi import APIRouter
from app.api.v1 import auth, clientes, proyectos, fallas, generacion, monitoreo, liquidaciones, ppa, asic, fronteras, alertas, contratos_servicio, informes, cumplimiento, mgs, evo_proxy, correlation, dashboard, solar, generacion_solar, garantias, notificaciones, api_keys, mapa, portafolios, proximos_energizar, representacion, reconectadores, om, costos_variables, starlink

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(auth.usuarios_router)
api_router.include_router(api_keys.router)
api_router.include_router(dashboard.router)
api_router.include_router(clientes.router)
api_router.include_router(proyectos.router)
api_router.include_router(portafolios.router)
api_router.include_router(fallas.router)
api_router.include_router(generacion.router)
api_router.include_router(monitoreo.router)
api_router.include_router(liquidaciones.router)
api_router.include_router(ppa.router)
api_router.include_router(asic.router)
api_router.include_router(fronteras.router)
api_router.include_router(alertas.router)
api_router.include_router(contratos_servicio.router)
api_router.include_router(informes.router)
api_router.include_router(cumplimiento.router)
api_router.include_router(mgs.router)
api_router.include_router(evo_proxy.router)
api_router.include_router(correlation.router)
api_router.include_router(solar.router)
api_router.include_router(generacion_solar.router)
api_router.include_router(garantias.router)
api_router.include_router(notificaciones.router)
api_router.include_router(mapa.router)
api_router.include_router(proximos_energizar.router)
api_router.include_router(representacion.router)
api_router.include_router(reconectadores.router)
api_router.include_router(om.router)
api_router.include_router(costos_variables.router)
api_router.include_router(starlink.router)
