# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidaciones', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoInversionista',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mandato_inversionistas',
            },
        ),
        migrations.CreateModel(
            name='FinanzasMandato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=255)),
                ('tercero', models.CharField(default='', max_length=255)),
                ('periodo', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('costo', 'costo')], max_length=7)),
                ('cmu', models.CharField(blank=True, max_length=20, null=True)),
                ('cmu_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('sin_firma', 'sin_firma'), ('firmado', 'firmado'), ('con_comentarios', 'con_comentarios'), ('corregido', 'corregido'), ('enviado_inversionista', 'enviado_inversionista')], default='sin_firma', max_length=21)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('fecha_envio_inversionista', models.DateField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('correo_ref', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'finanzas_mandatos',
                'unique_together': {('periodo', 'proyecto', 'tercero', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMandato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingresos', 'ingresos'), ('costos', 'costos')], max_length=8)),
                ('numero_mandato', models.CharField(blank=True, max_length=50, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('beneficiario_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiario_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'borrador'), ('enviado_revisoria', 'enviado_revisoria'), ('firmado', 'firmado'), ('entregado', 'entregado')], default='borrador', max_length=17)),
                ('fecha_generacion', models.DateField(blank=True, null=True)),
                ('fecha_envio_revisoria', models.DateField(blank=True, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('pa_aplica', models.BooleanField(default=False)),
                ('categoria_contable', models.CharField(blank=True, max_length=50, null=True)),
                ('total_ingresos_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_costos_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_retenciones_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_iva_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_neto_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('inversionista', models.ForeignKey(blank=True, db_column='inversionista_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='liquidacion_mandatos_por_inversionista_id', to='proyectos.proyectoinversionista')),
                ('liquidacion', models.ForeignKey(db_column='liquidacion_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mandatos', to='liquidaciones.liquidacion')),
            ],
            options={
                'db_table': 'liquidacion_mandatos',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMandatoLinea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_linea', models.CharField(choices=[('ingreso_bruto', 'ingreso_bruto'), ('ajuste_xm', 'ajuste_xm'), ('ajuste_unergy', 'ajuste_unergy'), ('ajuste_comercializacion', 'ajuste_comercializacion'), ('intereses', 'intereses'), ('otro_ingreso', 'otro_ingreso'), ('despacho', 'despacho'), ('ventas_en_bolsa', 'ventas_en_bolsa'), ('compras_en_bolsa', 'compras_en_bolsa'), ('redistribucion_ingresos', 'redistribucion_ingresos'), ('mantenimiento', 'mantenimiento'), ('arriendo', 'arriendo'), ('servicio_internet', 'servicio_internet'), ('poliza_cumplimiento', 'poliza_cumplimiento'), ('servicios_publicos_consumo', 'servicios_publicos_consumo'), ('cambio_equipos_medida', 'cambio_equipos_medida'), ('seguro', 'seguro'), ('otro_costo', 'otro_costo'), ('comercializacion', 'comercializacion'), ('representacion', 'representacion'), ('cgm', 'cgm'), ('administracion', 'administracion'), ('iva', 'iva'), ('retencion_fuente', 'retencion_fuente'), ('reteica', 'reteica'), ('ica_opex', 'ica_opex'), ('otro_impuesto', 'otro_impuesto'), ('porcentaje_participacion', 'porcentaje_participacion'), ('valor_a_pagar', 'valor_a_pagar')], max_length=26)),
                ('concepto', models.CharField(max_length=500)),
                ('valor_cop', models.DecimalField(decimal_places=2, max_digits=18)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('base_calculo_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('referencia_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('soporte_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('mandato', models.ForeignKey(db_column='mandato_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lineas', to='mandatos.liquidacionmandato')),
            ],
            options={
                'db_table': 'liquidacion_mandato_lineas',
            },
        ),
        migrations.CreateModel(
            name='MandatoCorreo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=998)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('remitente', models.CharField(max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=1000, null=True)),
                ('fuente', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=20)),
                ('requiere_revision', models.BooleanField(db_index=True, default=False)),
                ('detalle', models.JSONField()),
                ('revertido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mandato_correos',
                'unique_together': {('message_id',)},
            },
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmu', models.CharField(db_index=True, max_length=20)),
                ('periodo', models.DateField()),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente_envio', 'pendiente_envio'), ('enviado_revisoria', 'enviado_revisoria'), ('con_correcciones', 'con_correcciones'), ('corregido', 'corregido'), ('firmado', 'firmado'), ('enviado_inversionista', 'enviado_inversionista'), ('sin_inversionista', 'sin_inversionista')], default='pendiente_envio', max_length=21)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_envio_revisoria', models.DateField(blank=True, null=True)),
                ('fecha_firmado', models.DateField(blank=True, null=True)),
                ('fecha_envio_inversionista', models.DateField(blank=True, null=True)),
                ('pdf_firmado_ruta', models.CharField(blank=True, max_length=1000, null=True)),
                ('pdf_firmado_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('archivo_zip_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('correo_ref_revisoria', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_ref_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('inversionista', models.ForeignKey(blank=True, db_column='inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandatos_por_inversionista_id', to='mandatos.mandatoinversionista')),
            ],
            options={
                'db_table': 'mandatos',
                'unique_together': {('cmu', 'periodo')},
            },
        ),
    ]
