# Generated by Django 6.0.8 on 2026-09-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatocorreo',
            name='detalle',
            field=models.JSONField(default=dict),
        ),
    ]
