# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.DateField()),
                ('tipo_venta', models.CharField(choices=[('bolsa', 'bolsa'), ('ppa', 'ppa'), ('interno', 'interno'), ('autoconsumo', 'autoconsumo')], max_length=11)),
                ('estado', models.CharField(choices=[('iniciada', 'iniciada'), ('costos_registrados', 'costos_registrados'), ('xm_procesado', 'xm_procesado'), ('mandatos_emitidos', 'mandatos_emitidos'), ('en_contabilidad', 'en_contabilidad'), ('en_revisoria', 'en_revisoria'), ('facturado', 'facturado'), ('entregado', 'entregado')], default='iniciada', max_length=18)),
                ('fecha_inicio_proceso', models.DateField(blank=True, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('consecutivo_inicial_ingresos', models.IntegerField(blank=True, null=True)),
                ('consecutivo_inicial_costos', models.IntegerField(blank=True, null=True)),
                ('comprobante_contable_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_resultados_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('ingresos_energia_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('costos_comercializacion_xm_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('costos_operativos_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ingreso_neto_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ingreso_neto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('observaciones_resultados', models.TextField(blank=True, null=True)),
                ('informe_html', models.TextField(blank=True, null=True)),
                ('informe_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('generado_por', models.ForeignKey(db_column='generado_por_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='liquidaciones_por_generado_por_id', to='plataforma.usuario')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='liquidaciones_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'liquidaciones',
                'unique_together': {('periodo', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionCosto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_costo', models.CharField(choices=[('mantenimiento', 'mantenimiento'), ('internet', 'internet'), ('arriendo', 'arriendo'), ('polizas', 'polizas'), ('comercializacion_xm', 'comercializacion_xm'), ('servicios_publicos', 'servicios_publicos'), ('cambio_equipos_medida', 'cambio_equipos_medida'), ('otro', 'otro')], max_length=21)),
                ('descripcion', models.CharField(max_length=500)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_soporte', models.CharField(blank=True, max_length=100, null=True)),
                ('soporte_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('valor_cop', models.DecimalField(decimal_places=2, max_digits=18)),
                ('liquidacion', models.ForeignKey(db_column='liquidacion_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='costos', to='liquidaciones.liquidacion')),
            ],
            options={
                'db_table': 'liquidacion_costos',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionFactura',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('representacion', 'representacion'), ('cgm', 'cgm'), ('administracion_operacion', 'administracion_operacion')], max_length=24)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_soporte', models.CharField(blank=True, max_length=100, null=True)),
                ('soporte_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('valor_cop', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('emitida', 'emitida'), ('pagada', 'pagada'), ('vencida', 'vencida')], default='emitida', max_length=7)),
                ('liquidacion', models.ForeignKey(db_column='liquidacion_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='liquidaciones.liquidacion')),
                ('proyecto_inversionista', models.ForeignKey(blank=True, db_column='proyecto_inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_facturas_por_proyecto_inversionista_id', to='proyectos.proyectoinversionista')),
            ],
            options={
                'db_table': 'liquidacion_facturas',
            },
        ),
    ]
