# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEnergiaConsumo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('caso', models.CharField(max_length=20)),
                ('medidor_usado', models.CharField(blank=True, max_length=30, null=True)),
                ('energia_final_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('curva_final', models.JSONField(blank=True, null=True)),
                ('energia_cgm_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('estado_reporte', models.CharField(blank=True, max_length=20, null=True)),
                ('curva_medidor_principal', models.JSONField(blank=True, null=True)),
                ('curva_medidor_respaldo', models.JSONField(blank=True, null=True)),
                ('curva_respaldo_final', models.JSONField(blank=True, null=True)),
                ('respaldo_final_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('horas_rellenadas_historico', models.JSONField(blank=True, null=True)),
                ('horas_rellenadas_medidor_cruzado', models.JSONField(blank=True, null=True)),
                ('recuperacion_datos', models.CharField(blank=True, max_length=255, null=True)),
                ('revisar_manualmente', models.BooleanField(default=False)),
                ('editado_manualmente', models.BooleanField(default=False)),
                ('error_clasificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('enviado_quoia_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_quoia_ok', models.BooleanField(blank=True, null=True)),
                ('enviado_quoia_error', models.CharField(blank=True, max_length=500, null=True)),
                ('xm_process_id', models.CharField(blank=True, max_length=100, null=True)),
                ('xm_estado', models.CharField(blank=True, max_length=30, null=True)),
                ('xm_exitoso', models.BooleanField(blank=True, null=True)),
                ('xm_verificado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte_energia_consumo',
            },
        ),
        migrations.CreateModel(
            name='ReporteEnergiaExclusion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reporte_energia_exclusiones',
            },
        ),
        migrations.CreateModel(
            name='ReporteEnergiaGeneracion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('caso', models.IntegerField()),
                ('medidor_usado', models.CharField(blank=True, max_length=30, null=True)),
                ('energia_final_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('curva_final', models.JSONField(blank=True, null=True)),
                ('fp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fp_calculada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('error_final_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('energia_cgm_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('estado_reporte', models.CharField(blank=True, max_length=20, null=True)),
                ('energia_solenium_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('solenium_completo', models.BooleanField(blank=True, null=True)),
                ('nota_solenium', models.CharField(blank=True, max_length=100, null=True)),
                ('energia_medidor_principal_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('energia_medidor_respaldo_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('medidor_principal_completo', models.BooleanField(blank=True, null=True)),
                ('medidor_respaldo_completo', models.BooleanField(blank=True, null=True)),
                ('curva_respaldo_terceros', models.JSONField(blank=True, null=True)),
                ('curva_respaldo_final', models.JSONField(blank=True, null=True)),
                ('respaldo_final_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('curva_medidor_principal', models.JSONField(blank=True, null=True)),
                ('curva_medidor_respaldo', models.JSONField(blank=True, null=True)),
                ('curva_solenium_referencia', models.JSONField(blank=True, null=True)),
                ('curva_reconectador_referencia', models.JSONField(blank=True, null=True)),
                ('horas_rellenadas_reconectador', models.JSONField(blank=True, null=True)),
                ('horas_rellenadas_solenium', models.JSONField(blank=True, null=True)),
                ('horas_rellenadas_historico', models.JSONField(blank=True, null=True)),
                ('horas_rellenadas_medidor_cruzado', models.JSONField(blank=True, null=True)),
                ('recuperacion_datos', models.CharField(blank=True, max_length=255, null=True)),
                ('revisar_manualmente', models.BooleanField(default=False)),
                ('editado_manualmente', models.BooleanField(default=False)),
                ('error_clasificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('enviado_quoia_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_quoia_ok', models.BooleanField(blank=True, null=True)),
                ('enviado_quoia_error', models.CharField(blank=True, max_length=500, null=True)),
                ('xm_process_id', models.CharField(blank=True, max_length=100, null=True)),
                ('xm_estado', models.CharField(blank=True, max_length=30, null=True)),
                ('xm_exitoso', models.BooleanField(blank=True, null=True)),
                ('xm_verificado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte_energia_generacion',
            },
        ),
    ]
