# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energia', '0001_initial'),
        ('fronteras', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteenergiaconsumo',
            name='frontera',
            field=models.ForeignKey(db_column='frontera_id', on_delete=django.db.models.deletion.PROTECT, related_name='reporte_energia_consumo_por_frontera_id', to='fronteras.frontera'),
        ),
        migrations.AddField(
            model_name='reporteenergiaexclusion',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporte_energia_exclusiones_por_creado_por_id', to='plataforma.usuario'),
        ),
        migrations.AddField(
            model_name='reporteenergiaexclusion',
            name='frontera',
            field=models.ForeignKey(db_column='frontera_id', on_delete=django.db.models.deletion.PROTECT, related_name='reporte_energia_exclusiones_por_frontera_id', to='fronteras.frontera'),
        ),
        migrations.AddField(
            model_name='reporteenergiageneracion',
            name='frontera',
            field=models.ForeignKey(db_column='frontera_id', on_delete=django.db.models.deletion.PROTECT, related_name='reporte_energia_generacion_por_frontera_id', to='fronteras.frontera'),
        ),
        migrations.AlterUniqueTogether(
            name='reporteenergiaconsumo',
            unique_together={('fecha', 'frontera')},
        ),
        migrations.AlterUniqueTogether(
            name='reporteenergiageneracion',
            unique_together={('fecha', 'frontera')},
        ),
    ]
