# Generated by Django 6.0.8 on 2026-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionregistro',
            name='tipo',
            field=models.CharField(choices=[('pqr', 'pqr'), ('preventivo', 'preventivo'), ('correctivo', 'correctivo')], max_length=50),
        ),
    ]
