# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrArrendador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('responsable_iva', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('anticipo_pagado_desde', models.DateField(blank=True, null=True)),
                ('anticipo_pagado_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'arr_arrendador',
            },
        ),
        migrations.CreateModel(
            name='ArrDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('pago_id', models.IntegerField()),
                ('codigo_contrato', models.CharField(max_length=120)),
                ('tipo_documento', models.CharField(max_length=30)),
                ('nombre_archivo', models.CharField(max_length=500)),
                ('ruta_local', models.CharField(max_length=1000)),
                ('ruta_original', models.CharField(blank=True, max_length=1000, null=True)),
                ('nombre_secundario', models.CharField(blank=True, max_length=500, null=True)),
                ('ruta_secundario', models.CharField(blank=True, max_length=1000, null=True)),
                ('codigo_predio', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_cuenta_cobro', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_arrendatario', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'arr_documento',
            },
        ),
        migrations.CreateModel(
            name='ArrIpcTasa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=8)),
                ('confirmado', models.BooleanField(default=False)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'arr_ipc_tasas',
            },
        ),
        migrations.CreateModel(
            name='ArrProyecto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'arr_proyectos',
            },
        ),
        migrations.CreateModel(
            name='ArrSeleccionMensual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('incluido', models.BooleanField(default=True)),
                ('facturado', models.BooleanField(default=False)),
                ('valor_facturado_congelado', models.BigIntegerField(blank=True, null=True)),
                ('motivo_exclusion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'arr_seleccion_mensual',
            },
        ),
    ]
