# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arriendos', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrarrendador',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='arr_arrendador_por_contrato_id', to='contratos.contratoservicio'),
        ),
        migrations.AddField(
            model_name='arrdocumento',
            name='arr_arrendador',
            field=models.ForeignKey(blank=True, db_column='arr_arrendador_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arr_documento_por_arr_arrendador_id', to='arriendos.arrarrendador'),
        ),
    ]
