# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arriendos', '0002_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrdocumento',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arr_documento_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='arripctasa',
            unique_together={('año',)},
        ),
        migrations.AlterUniqueTogether(
            name='arrproyecto',
            unique_together={('codigo',)},
        ),
        migrations.AddField(
            model_name='arrdocumento',
            name='arr_proyecto',
            field=models.ForeignKey(blank=True, db_column='arr_proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arr_documento_por_arr_proyecto_id', to='arriendos.arrproyecto'),
        ),
        migrations.AddField(
            model_name='arrseleccionmensual',
            name='arr_arrendador',
            field=models.ForeignKey(blank=True, db_column='arr_arrendador_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arr_seleccion_mensual_por_arr_arrendador_id', to='arriendos.arrarrendador'),
        ),
        migrations.AddField(
            model_name='arrseleccionmensual',
            name='arr_proyecto',
            field=models.ForeignKey(blank=True, db_column='arr_proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arr_seleccion_mensual_por_arr_proyecto_id', to='arriendos.arrproyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='arrdocumento',
            unique_together={('arr_arrendador', 'arr_proyecto', 'pago_id', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='arrseleccionmensual',
            unique_together={('arr_arrendador', 'periodo')},
        ),
    ]
