# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoTrimestre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_index=True)),
                ('trimestre', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=160, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'retos_trimestre',
                'unique_together': {('anio', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='RetoMetrica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=40, null=True)),
                ('meta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('tipo_agregacion', models.CharField(default='suma', max_length=20)),
                ('direccion', models.CharField(default='mayor_mejor', max_length=20)),
                ('decimales', models.IntegerField(default=0)),
                ('responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('reto', models.ForeignKey(db_column='reto_id', on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='retos.retotrimestre')),
            ],
            options={
                'db_table': 'retos_metrica',
            },
        ),
        migrations.CreateModel(
            name='RetoValorSemanal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semana_inicio', models.DateField()),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_valor_semanal_por_actualizado_por_id', to='plataforma.usuario')),
                ('metrica', models.ForeignKey(db_column='metrica_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='retos.retometrica')),
            ],
            options={
                'db_table': 'retos_valor_semanal',
                'unique_together': {('metrica', 'semana_inicio')},
            },
        ),
    ]
