# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTasaServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=30)),
                ('iva_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retencion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reteiva_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reteica_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'cliente_tasa_servicio',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('operacional', 'operacional'), ('cgm', 'cgm'), ('liquidacion', 'liquidacion'), ('comercial', 'comercial'), ('contable', 'contable')], max_length=11)),
                ('recibe_notificaciones', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoAreaContacto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('operacional', 'operacional'), ('cgm', 'cgm'), ('liquidacion', 'liquidacion'), ('comercial', 'comercial'), ('contable', 'contable')], max_length=11)),
            ],
            options={
                'db_table': 'proyecto_area_contacto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('razon_social_nombre', models.CharField(max_length=255)),
                ('nit_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('natural', 'natural'), ('juridica', 'juridica')], max_length=8, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('iva_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retencion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reteica_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reteiva_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('origen_tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('origen_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('nit_cedula',)},
            },
        ),
        migrations.CreateModel(
            name='ClienteDocumentoComercial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('rut', 'rut'), ('certificado_bancario', 'certificado_bancario'), ('camara_comercio', 'camara_comercio'), ('oferta', 'oferta'), ('contrato', 'contrato')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'borrador'), ('enviado', 'enviado'), ('aceptado', 'aceptado'), ('firmado', 'firmado'), ('rechazado', 'rechazado')], default='borrador', max_length=9)),
                ('archivo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('archivo_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos_comerciales', to='clientes.cliente')),
            ],
            options={
                'db_table': 'cliente_documentos_comerciales',
            },
        ),
    ]
