# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('ppa', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientedocumentocomercial',
            name='ppa_contrato',
            field=models.ForeignKey(blank=True, db_column='ppa_contrato_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_comerciales', to='ppa.ppacontrato'),
        ),
        migrations.AddField(
            model_name='clientetasaservicio',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_servicio', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='clientetasaservicio',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_tasa_servicio_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contactos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='proyectoareacontacto',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_area_contacto_por_cliente_id', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='proyectoareacontacto',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_contactos', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='clientetasaservicio',
            unique_together={('cliente', 'proyecto', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together={('cliente', 'email', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='proyectoareacontacto',
            unique_together={('proyecto', 'tipo')},
        ),
    ]
