# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operaciones', 'Operaciones'), ('monitoreo', 'Monitoreo'), ('liquidaciones', 'Liquidaciones'), ('cgm', 'CGM'), ('solo_lectura', 'Solo lectura'), ('coordinador', 'Coordinador'), ('tecnico', 'Técnico'), ('comercial', 'Comercial')], max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alerta', 'alerta'), ('info', 'info'), ('accion', 'accion')], max_length=6)),
                ('titulo', models.CharField(max_length=500)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='InformeGuardado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('op', 'op'), ('fmo', 'fmo'), ('port', 'port'), ('ranking', 'ranking'), ('pm', 'pm')], max_length=7)),
                ('sub_project', models.CharField(max_length=200)),
                ('periodo_desde', models.CharField(max_length=10)),
                ('periodo_hasta', models.CharField(max_length=10)),
                ('periodo_display', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('html_content', models.TextField()),
                ('charts_data', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'borrador'), ('revisado', 'revisado'), ('aprobado', 'aprobado')], max_length=8)),
                ('creado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('editado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('correo_enviado', models.BooleanField()),
                ('correo_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.JSONField(blank=True, null=True)),
                ('miembros', models.JSONField(blank=True, null=True)),
                ('enviado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_guardados_por_aprobado_por_id', to='plataforma.usuario')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_guardados_por_creado_por_id', to='plataforma.usuario')),
                ('editado_por', models.ForeignKey(blank=True, db_column='editado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_guardados_por_editado_por_id', to='plataforma.usuario')),
                ('enviado_por', models.ForeignKey(blank=True, db_column='enviado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_guardados_por_enviado_por_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'informes_guardados',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('key_hash', models.CharField(max_length=255, unique=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=12, verbose_name='Prefijo')),
                ('scopes', models.JSONField(default=list, verbose_name='Alcances')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='plataforma.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
            },
        ),
    ]
