# Generated by Django 6.0.8 on 2026-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeguardado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'borrador'), ('revisado', 'revisado'), ('aprobado', 'aprobado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informeguardado',
            name='tipo',
            field=models.CharField(choices=[('op', 'op'), ('fmo', 'fmo'), ('port', 'port'), ('ranking', 'ranking'), ('pm', 'pm')], max_length=20),
        ),
    ]
