# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
        ('ppa', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmaMonitoreo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proyecto_nombre', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('alarm_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('source_data', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alarmas_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='StarlinkFactura',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('items_json', models.TextField()),
                ('agrupado_json', models.TextField()),
                ('cargos_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suma_items', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'starlink_facturas',
            },
        ),
        migrations.CreateModel(
            name='FallaCatCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=255)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fallas_cat_categorias',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='FallaCatEstado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('es_estado_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fallas_cat_estados',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='FallaCatPrioridad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
            ],
            options={
                'db_table': 'fallas_cat_prioridades',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='FallaCatResolucion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fallas_cat_resoluciones',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='FallaCatTipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipos', to='monitoreo.fallacatcategoria')),
            ],
            options={
                'db_table': 'fallas_cat_tipos',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_identificacion', models.DateField(db_index=True)),
                ('hora_identificacion', models.TimeField(blank=True, null=True)),
                ('fecha_ocurrencia', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('sla_limite_horas', models.IntegerField(blank=True, null=True)),
                ('sla_cumplido', models.BooleanField(blank=True, null=True)),
                ('fotos_urls', models.JSONField(blank=True, null=True)),
                ('notificacion', models.BooleanField(default=False)),
                ('kwh_perdidos_estimado', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('impacto_economico_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('acciones_correctivas', models.TextField(blank=True, null=True)),
                ('fecha_programada', models.DateField(blank=True, db_index=True, null=True)),
                ('categoria_codigo', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('subtipo_codigo', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('subtipo_detalle', models.TextField(blank=True, null=True)),
                ('clasificacion', models.JSONField(blank=True, null=True)),
                ('pendiente_reclasificar', models.BooleanField(default=False)),
                ('frontera_afecta_medicion', models.BooleanField(blank=True, null=True)),
                ('frontera_perdida_comunicacion', models.BooleanField(blank=True, null=True)),
                ('inversores_perdida_comunicacion', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alarma_monitoreo', models.ForeignKey(blank=True, db_column='alarma_monitoreo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_por_alarma_monitoreo_id', to='monitoreo.alarmamonitoreo')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_proyecto_id', to='proyectos.proyecto')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_registrado_por_id', to='plataforma.usuario')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_estado_id', to='monitoreo.fallacatestado')),
                ('prioridad', models.ForeignKey(db_column='prioridad_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_prioridad_id', to='monitoreo.fallacatprioridad')),
                ('resolucion', models.ForeignKey(blank=True, db_column='resolucion_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_resolucion_id', to='monitoreo.fallacatresolucion')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_por_tipo_id', to='monitoreo.fallacattipo')),
            ],
            options={
                'db_table': 'fallas',
                'unique_together': {('codigo_interno',)},
            },
        ),
        migrations.CreateModel(
            name='FallaIntervalo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('falla', models.ForeignKey(db_column='falla_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='intervalos', to='monitoreo.falla')),
            ],
            options={
                'db_table': 'fallas_intervalos',
            },
        ),
        migrations.CreateModel(
            name='FallaInversor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('potencia_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tipos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('falla', models.ForeignKey(db_column='falla_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inversores_afectados', to='monitoreo.falla')),
                ('proyecto_inversor', models.ForeignKey(blank=True, db_column='proyecto_inversor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='falla_inversores_por_proyecto_inversor_id', to='proyectos.proyectoinversor')),
            ],
            options={
                'db_table': 'falla_inversores',
            },
        ),
        migrations.CreateModel(
            name='FallaSeguimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_nuevo', models.ForeignKey(blank=True, db_column='estado_nuevo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_seguimientos_por_estado_nuevo_id', to='monitoreo.fallacatestado')),
                ('falla', models.ForeignKey(db_column='falla_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguimientos', to='monitoreo.falla')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fallas_seguimientos_por_usuario_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'fallas_seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'preventivo'), ('correctivo', 'correctivo'), ('predictivo', 'predictivo')], max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'programado'), ('en_ejecucion', 'en_ejecucion'), ('completado', 'completado'), ('cancelado', 'cancelado')], default='programado', max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenimientos_por_proyecto_id', to='proyectos.proyecto')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenimientos_por_registrado_por_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoImpacto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(default='scheduled', max_length=50)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('expected_generation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_generation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lost_energy_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financial_impact_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ppa_penalty_risk_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenimiento_impacto_por_created_by', to='plataforma.usuario')),
                ('falla', models.ForeignKey(blank=True, db_column='falla_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_impacto_por_falla_id', to='monitoreo.falla')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mantenimiento_impacto_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'mantenimiento_impacto',
            },
        ),
        migrations.CreateModel(
            name='StarlinkFacturaLinea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('excluido', models.BooleanField(default=False)),
                ('sin_iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('factura', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='monitoreo.starlinkfactura')),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starlink_factura_linea_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'starlink_factura_linea',
            },
        ),
        migrations.CreateModel(
            name='StarlinkMapeoSitio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patron', models.CharField(db_index=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='starlink_mapeo_sitio_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'starlink_mapeo_sitio',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('trigger_date', models.DateField()),
                ('days_to_expiration', models.IntegerField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('ppa', models.ForeignKey(db_column='ppa_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_por_ppa_id', to='ppa.ppacontrato')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_por_project_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'alertas',
                'unique_together': {('days_to_expiration', 'ppa')},
            },
        ),
    ]
