# Generated by Django 6.0.8 on 2026-09-04 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='trigger_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
