# Generated by Django 6.0.8 on 2026-09-04 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_alter_alerta_trigger_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallaintervalo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
