# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0002_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmFacturaMensual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('nombre_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('enlace_pdf', models.CharField(blank=True, max_length=2000, null=True)),
                ('ruta_local', models.CharField(blank=True, max_length=1000, null=True)),
                ('subido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'om_factura_mensual',
            },
        ),
        migrations.CreateModel(
            name='OmIpcTasa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=8)),
                ('confirmado', models.BooleanField(default=False)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'om_ipc_tasas',
                'unique_together': {('año',)},
            },
        ),
        migrations.CreateModel(
            name='ProyectoInformeOm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('elaborado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'borrador'), ('en_revision', 'en_revision'), ('aprobado', 'aprobado')], default='borrador', max_length=11)),
                ('empresa_contratista', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_energizacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_operacion', models.DateField(blank=True, null=True)),
                ('pendientes', models.JSONField()),
                ('checklist_fusion_solar', models.JSONField()),
                ('checklist_frontera', models.JSONField()),
                ('checklist_estacion_meteo', models.JSONField()),
                ('checklist_reconectador', models.JSONField()),
                ('objetivo_alcance', models.JSONField()),
                ('datos_generales', models.JSONField()),
                ('arquitectura_comunicacion', models.JSONField()),
                ('equipos', models.JSONField()),
                ('variables_monitoreadas', models.JSONField()),
                ('configuracion_monitoreo', models.JSONField()),
                ('protocolo_pruebas', models.JSONField()),
                ('eventos_operativos', models.JSONField()),
                ('observaciones', models.JSONField()),
                ('recomendaciones', models.JSONField()),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('firmas', models.JSONField()),
                ('evidencia_arquitectura', models.JSONField()),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_informe_om_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'proyecto_informe_om',
            },
        ),
        migrations.CreateModel(
            name='OmDocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('nombre_archivo', models.CharField(max_length=500)),
                ('ruta_local', models.CharField(max_length=1000)),
                ('numero_factura', models.CharField(blank=True, max_length=30, null=True)),
                ('total_sin_impuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_facturacion', models.DateField(blank=True, null=True)),
                ('cufe', models.CharField(blank=True, max_length=200, null=True)),
                ('procesado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='om_documento_proyecto_por_contrato_id', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'om_documento_proyecto',
                'unique_together': {('contrato', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='OmPaginaSinMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('pagina', models.IntegerField()),
                ('nombre_extraido', models.CharField(blank=True, max_length=300, null=True)),
                ('estrategia', models.CharField(blank=True, max_length=30, null=True)),
                ('razon', models.CharField(max_length=200)),
                ('numero_factura', models.CharField(blank=True, max_length=30, null=True)),
                ('muestra_texto', models.CharField(blank=True, max_length=500, null=True)),
                ('origen', models.CharField(default='upload', max_length=20)),
                ('resuelto', models.BooleanField(default=False)),
                ('asignado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato_id_asignado', models.ForeignKey(blank=True, db_column='contrato_id_asignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='om_pagina_sin_match_por_contrato_id_asignado', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'om_pagina_sin_match',
                'unique_together': {('pagina', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='OmSeleccionMensual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('incluido', models.BooleanField(default=True)),
                ('facturado', models.BooleanField(default=False)),
                ('valor_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_facturado_congelado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('motivo_exclusion', models.CharField(blank=True, max_length=500, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='om_seleccion_mensual_por_contrato_id', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'om_seleccion_mensual',
                'unique_together': {('contrato', 'periodo')},
            },
        ),
    ]
