# Generated by Django 6.0.8 on 2026-09-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='arquitectura_comunicacion',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='checklist_estacion_meteo',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='checklist_frontera',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='checklist_fusion_solar',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='checklist_reconectador',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='configuracion_monitoreo',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='datos_generales',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='equipos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='eventos_operativos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='evidencia_arquitectura',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='firmas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='objetivo_alcance',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='observaciones',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='pendientes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='protocolo_pruebas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='recomendaciones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='proyectoinformeom',
            name='variables_monitoreadas',
            field=models.JSONField(default=list),
        ),
    ]
