# Generated by Django 6.0.8 on 2026-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0002_alter_proyectoinformeom_arquitectura_comunicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omseleccionmensual',
            name='valor_facturado_congelado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='omseleccionmensual',
            name='valor_manual',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
