# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IppMensual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ipp_mensual',
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PpaContrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_codigo_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_interno', models.CharField(blank=True, max_length=200, null=True)),
                ('comprador_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('comprador_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('vendedor_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tarifa_base', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('indice_indexacion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodicidad_indexacion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_indexacion_base', models.CharField(blank=True, max_length=7, null=True)),
                ('valor_indexacion_base', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cantidad_minima_kwh_mes', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('cantidad_maxima_kwh_mes', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('periodicidad_facturacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_pago', models.IntegerField(blank=True, null=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=500, null=True)),
                ('gescon_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('gescon_fecha_inicio', models.DateField(blank=True, null=True)),
                ('gescon_fecha_fin', models.DateField(blank=True, null=True)),
                ('gescon_precio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('gescon_cantidades_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('codigo_sic', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_contrato', models.CharField(blank=True, default='venta', max_length=20, null=True)),
                ('renovacion_automatica', models.BooleanField(blank=True, null=True)),
                ('es_comunidad_energetica', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comprador', models.ForeignKey(blank=True, db_column='comprador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppa_contratos_por_comprador_id', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppa_contratos_por_vendedor_id', to='clientes.cliente')),
            ],
            options={
                'db_table': 'ppa_contratos',
            },
        ),
        migrations.CreateModel(
            name='PpaContratoProyecto',
            fields=[
                ('pk', models.CompositePrimaryKey('contrato_id', 'proyecto_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_vinculados', to='ppa.ppacontrato')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_ppa', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'ppa_contrato_proyectos',
            },
        ),
        migrations.CreateModel(
            name='PpaResponsable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('incluir_en_cumplimiento', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ppa_responsables',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.AddField(
            model_name='ppacontrato',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='ppa.pparesponsable'),
        ),
        migrations.CreateModel(
            name='PpaCompromisoEnergia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('energia_minima', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('energia_maxima', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('cantidad_proyectos', models.IntegerField(blank=True, default=0, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='ppa.ppacontrato')),
            ],
            options={
                'db_table': 'ppa_compromisos_energia',
                'unique_together': {('año', 'contrato', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PpaTarifa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tarifa', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='ppa.ppacontrato')),
            ],
            options={
                'db_table': 'ppa_tarifas',
                'unique_together': {('año', 'contrato', 'mes')},
            },
        ),
    ]
