"""Catalogo de parametros unicos del sistema de medida (proceso SIC/ASIC).

GENERADO por scripts/generar_catalogo_parametros.py a partir de la hoja
"Definicion de campos" del formato oficial de Hoja de Vida (CREG 038/2014).
No editar a mano: ajustar el generador y regenerar.

Cada entrada es un dato UNICO del proyecto. Los documentos que lo contienen no
lo repiten: lo referencian por su clave (ver mapa_documentos.py). Ese es el
principio rector del modulo -- un dato, una fila, una fuente de verdad.

  clave         identificador estable "<grupo>.<nombre>", unico en el catalogo
  titulo        etiqueta para la UI
  tipo          TEXTO | NUMERO | FECHA | CATEGORIA | LISTA | TABLA
  requerido     lo exige el formato oficial
  ambito        PROYECTO (un valor por proyecto) | EQUIPO (uno por equipo y posicion)
  equipo_tipos  tipos de equipo a los que aplica la definicion (ambito EQUIPO)
  instancias    cuantos equipos de ese tipo admite la frontera (TC y TP: 3)
  etiquetas     nombre de cada instancia cuando aplica (p. ej. Fase R/S/T)
  origen_hv     numerales de la Hoja de Vida de donde sale (trazabilidad)
  columnas      solo para tipo TABLA: columnas de la sub-tabla
"""

from __future__ import annotations

PARAMETROS: list[dict] = [

    # --- Registro de novedades -----------------------------------------
    {"clave": "novedad.fecha_de_la_ultima_novedad", "titulo": 'Fecha de la ultima novedad', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "novedad", "instancias": 1, "origen_hv": ['1.1']},
    {"clave": "novedad.fecha_de_verificacion_inicial", "titulo": 'Fecha de Verificación inicial', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "novedad", "instancias": 1, "origen_hv": ['1.1.1']},
    {"clave": "novedad.tipo_de_novedad", "titulo": 'Tipo de Novedad', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "novedad", "instancias": 1, "origen_hv": ['1.2']},
    {"clave": "novedad.estado_de_la_frontera", "titulo": 'Estado de la Frontera', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "novedad", "instancias": 1, "origen_hv": ['1.3']},

    # --- Informacion general de la frontera ----------------------------
    {"clave": "frontera.nombre_frontera", "titulo": 'Nombre Frontera', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.1']},
    {"clave": "frontera.nombre_de_usuario", "titulo": 'Nombre de Usuario', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.2']},
    {"clave": "frontera.direccion", "titulo": 'Dirección', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.3']},
    {"clave": "frontera.localizacion", "titulo": 'Localización', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.4']},
    {"clave": "frontera.ciudad_municipio", "titulo": 'Ciudad/Municipio', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.5']},
    {"clave": "frontera.latitud", "titulo": 'Coordenadas - latitud', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.6']},
    {"clave": "frontera.longitud", "titulo": 'Coordenadas - longitud', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.7']},
    {"clave": "frontera.departamento", "titulo": 'Departamento', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.8']},
    {"clave": "frontera.agente_rf", "titulo": 'Agente RF', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.9']},
    {"clave": "frontera.codigo_sic_rf", "titulo": 'Codigo SIC RF', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.10']},
    {"clave": "frontera.exportador_fisico", "titulo": 'Exportador Físico', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.11']},
    {"clave": "frontera.codigo_sic_exp", "titulo": 'Codigo SIC EXP', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.12']},
    {"clave": "frontera.fecha_de_registro", "titulo": 'Fecha de Registro (matricula)', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.13']},
    {"clave": "frontera.tension_de_servicio", "titulo": 'Tensión de Servicio (kV)', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.14']},
    {"clave": "frontera.capacidad_instalada", "titulo": 'Capacidad Instalada (kVA)', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.15']},
    {"clave": "frontera.conexion", "titulo": 'Conexión', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.16']},
    {"clave": "frontera.clase_de_servicio", "titulo": 'Clase de Servicio', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.17']},
    {"clave": "frontera.estrato", "titulo": 'Estrato', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.18']},
    {"clave": "frontera.factor_liq_externo", "titulo": 'Factor liq. Externo', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.19']},
    {"clave": "frontera.factor_liq_interno", "titulo": 'Factor liq. Interno', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.20']},
    {"clave": "frontera.factor_de_ajuste_del_punto_de_medicion", "titulo": 'Factor de ajuste del punto de medición', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.21']},
    {"clave": "frontera.frontera_embebida", "titulo": 'Frontera Embebida', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.22']},
    {"clave": "frontera.codigo_sic_frontera_principal", "titulo": 'Código SIC Frontera Principal', "tipo": "TEXTO", "requerido": False, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.23']},
    {"clave": "frontera.tipo_de_frontera", "titulo": 'Tipo de Frontera', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.24']},
    {"clave": "frontera.clasificacion_de_punto_de_medicion", "titulo": 'Clasificación de punto de medición', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.25']},
    {"clave": "frontera.fecha_planificada", "titulo": 'Fecha planificada', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.26.1']},
    {"clave": "frontera.fecha_ejecutada", "titulo": 'Fecha ejecutada', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.26.2']},
    {"clave": "frontera.calibracion_del_medidor", "titulo": 'Calibración del medidor', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.26.3']},
    {"clave": "frontera.pruebas_de_rutina", "titulo": 'Pruebas de Rutina', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.26.4']},
    {"clave": "frontera.estado_mto", "titulo": 'Estado mto.', "tipo": "LISTA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.26.5']},
    {"clave": "frontera.anexos", "titulo": 'Anexos', "tipo": "CATEGORIA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "frontera", "instancias": 1, "origen_hv": ['2.27']},

    # --- Medidores -----------------------------------------------------
    {"clave": "medidor.ubicacion_de_medidor", "titulo": 'Ubicación de Medidor', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.1', '5.1']},
    {"clave": "medidor.propiedad_medidor", "titulo": 'Propiedad Medidor', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.2', '5.2']},
    {"clave": "medidor.numero_de_serie", "titulo": 'Número de Serie', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.3', '5.3']},
    {"clave": "medidor.marca", "titulo": 'Marca', "tipo": "LISTA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.4', '5.4']},
    {"clave": "medidor.modelo", "titulo": 'Modelo (Referencia)', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.5', '5.5']},
    {"clave": "medidor.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.6', '5.6']},
    {"clave": "medidor.ano_de_fabricacion", "titulo": 'Año de Fabricación', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.7', '5.7']},
    {"clave": "medidor.proveedor_o_representante", "titulo": 'Proveedor o representante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.8', '5.8']},
    {"clave": "medidor.tecnologia_del_medidor", "titulo": 'Tecnología del Medidor', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.9', '5.9']},
    {"clave": "medidor.conexion", "titulo": 'Conexión', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.10', '5.10']},
    {"clave": "medidor.numero_de_elementos_de_la_conexion", "titulo": 'Número de elementos de la conexión', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.10.1', '5.10.1']},
    {"clave": "medidor.sentido_de_medicion", "titulo": 'Sentido de Medición', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.11', '5.11']},
    {"clave": "medidor.numero_de_hilos", "titulo": 'Número de Hilos', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.12', '5.12']},
    {"clave": "medidor.numero_de_fases", "titulo": 'Número de Fases', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.13', '5.13']},
    {"clave": "medidor.tipo_de_registrador", "titulo": 'Tipo de Registrador', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.14', '5.14']},
    {"clave": "medidor.cantidad_enteros", "titulo": 'Cantidad Enteros', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.15', '5.15']},
    {"clave": "medidor.cantidad_decimales", "titulo": 'Cantidad Decimales', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.16', '5.16']},
    {"clave": "medidor.tens_nominal", "titulo": 'Tens. Nominal (V)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.17', '5.17']},
    {"clave": "medidor.indice_clase_activa", "titulo": 'Indice de clase - activa (%)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.18', '5.18']},
    {"clave": "medidor.constante_activa", "titulo": 'Constante - activa', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.19', '5.19']},
    {"clave": "medidor.unidad_constante_activa", "titulo": 'Unidad de la constante - activa', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.20', '5.20']},
    {"clave": "medidor.frecuencia", "titulo": 'Frecuencia (Hz)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.21', '5.24']},
    {"clave": "medidor.ib", "titulo": 'Ib (A)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.22', '5.25']},
    {"clave": "medidor.imax", "titulo": 'Imax (A)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.23', '5.26']},
    {"clave": "medidor.in", "titulo": 'In (A)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.24', '5.27']},
    {"clave": "medidor.canal_impor_activa", "titulo": 'Canal de importacion - activa', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.25', '5.28']},
    {"clave": "medidor.canal_expor_activa", "titulo": 'Canal de exportacion - activa', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.26', '5.29']},
    {"clave": "medidor.sellos", "titulo": 'Sellos instalados', "tipo": "TABLA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.27', '5.32'], "columnas": ['ubicacion', 'serie', 'tipo', 'color', 'fecha_instalacion', 'fecha_retiro', 'propiedad']},
    {"clave": "medidor.fecha_entrada_en_operacion", "titulo": 'Fecha Entrada en Operación', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.28', '5.33']},
    {"clave": "medidor.fecha_calibracion", "titulo": 'Fecha Calibración', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.29', '5.34']},
    {"clave": "medidor.fecha_retiro_del_medidor", "titulo": 'Fecha Retiro del Medidor', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.30', '5.35']},
    {"clave": "medidor.memoria", "titulo": 'Memoria', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.31', '5.36']},
    {"clave": "medidor.cap_mem_mb", "titulo": 'Cap. Mem. MB', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.32', '5.37', '5.37.1']},
    {"clave": "medidor.sistema_de_almacenamiento_de_datos", "titulo": 'Sistema de almacenamiento de datos', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.32.1']},
    {"clave": "medidor.cambio_bateria", "titulo": 'Cambio Batería', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.33', '5.38']},
    {"clave": "medidor.software_de_lectura_local", "titulo": 'Software de Lectura Local', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.34', '5.39']},
    {"clave": "medidor.software_de_lectura_remota", "titulo": 'Software de Lectura Remota', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.35', '5.40']},
    {"clave": "medidor.esquemas_de_seguridad", "titulo": 'Esquemas de seguridad', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.36', '5.41']},
    {"clave": "medidor.puertos_de_comunicacion", "titulo": 'Puertos de Comunicación', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.37', '5.42']},
    {"clave": "medidor.cert_conformidad_numero", "titulo": 'Número', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.38.1', '5.43.1']},
    {"clave": "medidor.cert_conformidad_fecha_de_emision", "titulo": 'Fecha de emisión', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.38.2', '5.43.2']},
    {"clave": "medidor.cert_conformidad_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.38.3', '5.43.3']},
    {"clave": "medidor.otras_declaraciones_o_informes", "titulo": 'Otras declaraciones o informes', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.39', '5.44']},
    {"clave": "medidor.cert_calibracion_numero", "titulo": 'Número', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.40.1', '5.45.1']},
    {"clave": "medidor.cert_calibracion_fecha_de_emision", "titulo": 'Fecha de emisión', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.40.2', '5.45.2']},
    {"clave": "medidor.cert_calibracion_laboratorio", "titulo": 'Laboratorio', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.40.3', '5.45.3']},
    {"clave": "medidor.anexos", "titulo": 'Anexos', "tipo": "CATEGORIA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['3.41', '5.46']},
    {"clave": "medidor.indice_clase_reactiva", "titulo": 'Indice de clase - reactiva (%)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['4.18', '5.21']},
    {"clave": "medidor.constante_reactiva", "titulo": 'Constante - reactiva', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['4.19', '5.22']},
    {"clave": "medidor.unidad_constante_reactiva", "titulo": 'Unidad de la constante - reactiva', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['4.20', '5.23']},
    {"clave": "medidor.canal_impor_reactiva", "titulo": 'Canal de importacion - reactiva', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['4.25', '5.30']},
    {"clave": "medidor.canal_expor_reactiva", "titulo": 'Canal de exportacion - reactiva', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MEDIDOR_PRINCIPAL', 'MEDIDOR_RESPALDO'], "grupo": "medidor", "instancias": 1, "origen_hv": ['4.26', '5.31']},

    # --- Transformadores de corriente ----------------------------------
    {"clave": "tc.numero_de_serie", "titulo": 'Número de Serie', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.modelo", "titulo": 'Modelo (Referencia)', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.proveedor_o_representante", "titulo": 'Proveedor o Representante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.4'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.ano_de_fabricacion", "titulo": 'Año de Fabricación', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.5'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.burden", "titulo": 'Burden (VA)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.6'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cargas_para_compensacion_de_burden", "titulo": 'Cargas para compensación de Burden (VA)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.6.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.frecuencia", "titulo": 'Frecuencia (Hz)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.7'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.clase_de_exactitud", "titulo": 'Clase de exactitud (%)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.8'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.tension_nominal", "titulo": 'Tensión nominal (V)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.9'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.corriente_termica_ith", "titulo": 'Corriente térmica-Ith (kA)', "tipo": "NUMERO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.10'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.corriente_dinamica_idin", "titulo": 'Corriente dinámica-Idin (kA)', "tipo": "NUMERO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.11'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.fecha_entrada_en_operacion", "titulo": 'Fecha Entrada en Operación', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.12'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.fecha_de_retiro", "titulo": 'Fecha de Retiro', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.13'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.corriente_primaria_nominal_devanado_1", "titulo": 'Corriente Primaria nominal (A) Devanado 1', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.14'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.corriente_primaria_nominal_devanado_2", "titulo": 'Corriente Primaria nominal (A) Devanado 2', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.15'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.corriente_secundaria_nominal", "titulo": 'Corriente Secundaria nominal (A)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.16'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.relacion_transformacion", "titulo": 'Relación Transformación', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.17'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.relacion_transformacion_en_servicio", "titulo": 'Relación Transformación en servicio', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.18'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.sellos", "titulo": 'Sellos instalados', "tipo": "TABLA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.19'], "etiquetas": ['Fase R', 'Fase S', 'Fase T'], "columnas": ['ubicacion', 'serie', 'tipo', 'color', 'fecha_instalacion', 'fecha_retiro', 'propiedad']},
    {"clave": "tc.cert_calibracion_numero_certificado_1ra_relacion", "titulo": 'Número Certificado 1ra relación', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_calibracion_fecha_de_emision", "titulo": 'Fecha de Emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_calibracion_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.4'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_calibracion_conformidad", "titulo": 'Conformidad', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.4.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_calibracion_declaracion_de_fabricante", "titulo": 'Declaración de fabricante', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.4.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_calibracion_informe_de_recepcion", "titulo": 'Informe de recepción', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.20.4.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_pruebas_rutina_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.21.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.cert_pruebas_rutina_fecha_de_emision", "titulo": 'Fecha de Emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.21.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tc.anexos", "titulo": 'Anexos', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TC'], "grupo": "tc", "instancias": 3, "origen_hv": ['6.22'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},

    # --- Transformadores de tension ------------------------------------
    {"clave": "tp.numero_de_serie", "titulo": 'Número de Serie', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.modelo", "titulo": 'Modelo (Referencia)', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.proveedor_o_representante", "titulo": 'Proveedor o Representante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.4'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.ano_de_fabricacion", "titulo": 'Año de Fabricación', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.5'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.tension_primaria_nominal", "titulo": 'Tensión Primaria nominal (kV)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.6'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.tension_secundaria_nominal", "titulo": 'Tensión Secundaria nominal (V)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.7'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.tension_de_servicio", "titulo": 'Tensión de Servicio (kV)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.8'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.relacion_transformacion", "titulo": 'Relación Transformación', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.9'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.burden", "titulo": 'Burden (VA)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.10'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cargas_para_compensacion_de_burden", "titulo": 'Cargas para compensación de Burden (VA)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.10.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.frecuencia", "titulo": 'Frecuencia (Hz)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.11'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.clase_de_exactitud", "titulo": 'Clase de exactitud (%)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.12'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.fecha_entrada_en_operacion", "titulo": 'Fecha Entrada en Operación', "tipo": "FECHA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.13'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.fecha_de_retiro", "titulo": 'Fecha de Retiro', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.14'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.sellos", "titulo": 'Sellos instalados', "tipo": "TABLA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.15'], "etiquetas": ['Fase R', 'Fase S', 'Fase T'], "columnas": ['ubicacion', 'serie', 'tipo', 'color', 'fecha_instalacion', 'fecha_retiro', 'propiedad']},
    {"clave": "tp.cert_calibracion_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_calibracion_fecha_de_emision", "titulo": 'Fecha de Emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_calibracion_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_calibracion_conformidad", "titulo": 'Conformidad', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.4.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_calibracion_declaracion_de_fabricante", "titulo": 'Declaración de fabricante', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.4.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_calibracion_informe_de_recepcion", "titulo": 'Informe de recepción', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.16.4.3'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_pruebas_rutina_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.17.1'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.cert_pruebas_rutina_fecha_de_emision", "titulo": 'Fecha de Emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.17.2'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},
    {"clave": "tp.anexos", "titulo": 'Anexos', "tipo": "CATEGORIA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['TP'], "grupo": "tp", "instancias": 3, "origen_hv": ['7.18'], "etiquetas": ['Fase R', 'Fase S', 'Fase T']},

    # --- Conductores de senal de corriente -----------------------------
    {"clave": "conductor.calibre", "titulo": 'Calibre', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.1', '8.2.1']},
    {"clave": "conductor.denominacion", "titulo": 'Denominación', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.2', '8.2.2']},
    {"clave": "conductor.longitud", "titulo": 'Longitud (m)', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.3', '8.2.3']},
    {"clave": "conductor.no_de_conductores", "titulo": 'No. de conductores', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.4', '8.2.4']},
    {"clave": "conductor.mat_cond", "titulo": 'Mat Cond.', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.6', '8.2.6']},
    {"clave": "conductor.cert_conformidad_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.7.1', '8.2.7.1']},
    {"clave": "conductor.cert_conformidad_fecha_de_emision", "titulo": 'Fecha de emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.7.2', '8.2.7.2']},
    {"clave": "conductor.cert_conformidad_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.7.3', '8.2.7.3']},
    {"clave": "conductor.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_CORRIENTE', 'CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.1.8', '8.2.8']},

    # --- Conductores de senal de tension -------------------------------
    {"clave": "conductor.error_asociado_al_cableado", "titulo": 'Error asociado al cableado [%]', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR_TENSION'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.2.9']},

    # --- Conductores ---------------------------------------------------
    {"clave": "conductor.anexos", "titulo": 'Anexos', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CONDUCTOR'], "grupo": "conductor", "instancias": 1, "origen_hv": ['8.3']},

    # --- Celda o caja del medidor --------------------------------------
    {"clave": "celda.cert_conformidad_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.1.1', '9.2.1.1', '9.3.1.1']},
    {"clave": "celda.cert_conformidad_fecha_de_emision", "titulo": 'Fecha de emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.1.2', '9.2.1.2', '9.3.1.2']},
    {"clave": "celda.cert_conformidad_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.1.3', '9.2.1.3', '9.3.1.3']},
    {"clave": "celda.cert_conformidad_tipo_de_conformidad_de_producto", "titulo": 'Tipo de Conformidad de Producto', "tipo": "CATEGORIA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.1.4', '9.2.1.4', '9.3.1.4']},
    {"clave": "celda.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.2', '9.2.2', '9.3.2']},
    {"clave": "celda.serie", "titulo": 'Serie', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.3.1', '9.2.3.1', '9.3.3.1']},
    {"clave": "celda.tipo", "titulo": 'Tipo', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.3.2', '9.2.3.2', '9.3.3.2']},
    {"clave": "celda.color", "titulo": 'Color', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['CELDA_MEDIDOR', 'CELDA_TRAFOS', 'CELDA_OTRA'], "grupo": "celda", "instancias": 1, "origen_hv": ['9.1.3.3', '9.2.3.3', '9.3.3.3']},

    # --- Bornera de prueba ---------------------------------------------
    {"clave": "bornera.tipo_bornera", "titulo": 'Tipo Bornera', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.1']},
    {"clave": "bornera.sellos", "titulo": 'Sellos instalados', "tipo": "TABLA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.2'], "columnas": ['ubicacion', 'serie', 'tipo', 'color', 'fecha_instalacion', 'fecha_retiro', 'propiedad']},
    {"clave": "bornera.cert_conformidad_numero", "titulo": 'Número', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.3.1']},
    {"clave": "bornera.cert_conformidad_fecha_de_emision", "titulo": 'Fecha de emisión', "tipo": "FECHA", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.3.2']},
    {"clave": "bornera.cert_conformidad_ente_emisor", "titulo": 'Ente Emisor', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.3.3']},
    {"clave": "bornera.cert_conformidad_tipo_de_conformidad_de_producto", "titulo": 'Tipo de Conformidad de Producto', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.3.4']},
    {"clave": "bornera.fabricante", "titulo": 'Fabricante', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['BORNERA'], "grupo": "bornera", "instancias": 1, "origen_hv": ['10.4']},

    # --- Comunicaciones ------------------------------------------------
    {"clave": "modem.numero_de_serie_modem", "titulo": 'Número de Serie Modem', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.1', '12.1']},
    {"clave": "modem.marca_modem", "titulo": 'Marca Modem', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.2', '12.2']},
    {"clave": "modem.ip", "titulo": 'IP', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.3', '12.3']},
    {"clave": "modem.puerto", "titulo": 'Puerto', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.3.1', '12.3.1']},
    {"clave": "modem.apn", "titulo": 'APN', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.4', '12.4']},
    {"clave": "modem.imei", "titulo": 'IMEI', "tipo": "TEXTO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.5', '12.5']},
    {"clave": "modem.comm_port_address", "titulo": 'Comm port address', "tipo": "TEXTO", "requerido": False, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.6', '12.6']},
    {"clave": "modem.no_telefonico", "titulo": 'No. telefónico', "tipo": "NUMERO", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.7', '12.7']},
    {"clave": "modem.operador", "titulo": 'Operador', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.8', '12.8']},
    {"clave": "modem.medio_de_comunicacion", "titulo": 'Medio de Comunicación', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.9', '12.9']},
    {"clave": "modem.reporte_de_datos", "titulo": 'Reporte de datos', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.10', '12.10']},
    {"clave": "modem.anexos", "titulo": 'Anexos', "tipo": "CATEGORIA", "requerido": True, "ambito": "EQUIPO", "equipo_tipos": ['MODEM_PRINCIPAL', 'MODEM_RESPALDO'], "grupo": "modem", "instancias": 1, "origen_hv": ['11.11', '12.11']},

    # --- Persona designada por el RF -----------------------------------
    {"clave": "responsable.nombre", "titulo": 'Nombre', "tipo": "TEXTO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "responsable", "instancias": 1, "origen_hv": ['18.1']},
    {"clave": "responsable.documento", "titulo": 'Documento', "tipo": "NUMERO", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "responsable", "instancias": 1, "origen_hv": ['18.2']},
    {"clave": "responsable.fecha_de_impresion", "titulo": 'Fecha de Impresión (Vigencia)', "tipo": "FECHA", "requerido": True, "ambito": "PROYECTO", "equipo_tipos": [''], "grupo": "responsable", "instancias": 1, "origen_hv": ['18.3']},
]

PARAMETROS_POR_CLAVE: dict[str, dict] = {p['clave']: p for p in PARAMETROS}
