# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('revisado', 'revisado'), ('aprobado', 'aprobado')], default='pendiente', max_length=9)),
                ('enlace_factura', models.CharField(blank=True, max_length=1000, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('poliza_om', models.BooleanField(default=False)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('valor_poliza', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estructura', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paneles', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('inversores', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('otros', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_total_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('link_estudio_suelos', models.CharField(blank=True, max_length=500, null=True)),
                ('ipp_base', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ipp_base_fecha', models.DateField(blank=True, null=True)),
                ('ipp_provisional', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ipp_provisional_fecha', models.DateField(blank=True, null=True)),
                ('tarifa_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('generacion_anual_p90_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_lucro_cesante', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polizas',
            },
        ),
        migrations.CreateModel(
            name='ContratoServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio_aplica', models.CharField(choices=[('representacion', 'representacion'), ('cgm', 'cgm'), ('rec', 'rec'), ('mantenimiento', 'mantenimiento'), ('arriendo', 'arriendo'), ('internet', 'internet')], max_length=14)),
                ('contratante_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contratante_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('prestador_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('prestador_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('tiene_cgm', models.BooleanField(default=False)),
                ('cgm_codigo_sic', models.CharField(blank=True, max_length=20, null=True)),
                ('rec_cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('rec_precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rec_vintage', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tarifa_base', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('periodicidad_pago', models.CharField(blank=True, choices=[('mensual', 'mensual'), ('bimestral', 'bimestral'), ('trimestral', 'trimestral'), ('semestral', 'semestral'), ('anual', 'anual')], max_length=10, null=True)),
                ('indice_indexacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'vigente'), ('vencido', 'vencido'), ('terminado', 'terminado'), ('en_renovacion', 'en_renovacion')], default='vigente', max_length=13)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('fecha_inicio_om', models.DateField(blank=True, null=True)),
                ('renovacion_automatica', models.BooleanField(blank=True, null=True)),
                ('fecha_indexacion', models.DateField(blank=True, null=True)),
                ('responsable_iva', models.BooleanField(default=False)),
                ('estado_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_datos_gb', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad_mbps', models.IntegerField(blank=True, null=True)),
                ('tipo_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_router', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_kit', models.CharField(blank=True, max_length=100, null=True)),
                ('latencia_ms', models.IntegerField(blank=True, null=True)),
                ('wifi_seguridad', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tarifa_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('indexacion_anual', models.JSONField(blank=True, null=True)),
                ('indexacion_mensual', models.JSONField(blank=True, null=True)),
                ('inversionista_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('portafolio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sun_factory', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_proyecto_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('tarifa_admin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('tarifa_cgm', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tarifa_representacion', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('indexacion_cgm', models.JSONField(blank=True, null=True)),
                ('indexacion_representacion', models.JSONField(blank=True, null=True)),
                ('contratante', models.ForeignKey(blank=True, db_column='contratante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_contratante_id', to='clientes.cliente')),
                ('inversionista', models.ForeignKey(blank=True, db_column='inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_inversionista_id', to='clientes.cliente')),
                ('prestador', models.ForeignKey(blank=True, db_column='prestador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_prestador_id', to='clientes.cliente')),
            ],
            options={
                'db_table': 'contratos_servicio',
            },
        ),
    ]
