# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoservicio',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos_servicio_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_servicio_por_contrato_id', to='contratos.contratoservicio'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='polizas', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='pagoservicio',
            unique_together={('año', 'contrato', 'mes')},
        ),
    ]
