# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadoferta',
            name='contrato_servicio',
            field=models.ForeignKey(blank=True, db_column='contrato_servicio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidad_ofertas_por_contrato_servicio_id', to='contratos.contratoservicio'),
        ),
    ]
