# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_initial'),
        ('fronteras', '0002_initial'),
        ('ppa', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadoferta',
            name='operador_red',
            field=models.ForeignKey(blank=True, db_column='operador_red_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidad_ofertas_por_operador_red_id', to='fronteras.operadorred'),
        ),
        migrations.AddField(
            model_name='oportunidadoferta',
            name='oportunidad',
            field=models.ForeignKey(db_column='oportunidad_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ofertas', to='comercial.oportunidad'),
        ),
        migrations.AddField(
            model_name='oportunidadoferta',
            name='ppa_contrato',
            field=models.ForeignKey(blank=True, db_column='ppa_contrato_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidad_ofertas_por_ppa_contrato_id', to='ppa.ppacontrato'),
        ),
        migrations.AddField(
            model_name='oportunidadoferta',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidad_ofertas_por_proyecto_id', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='oportunidadgestion',
            name='oferta',
            field=models.ForeignKey(blank=True, db_column='oferta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidad_gestiones_por_oferta_id', to='comercial.oportunidadoferta'),
        ),
        migrations.AddField(
            model_name='oportunidadestadohistorial',
            name='oferta',
            field=models.ForeignKey(blank=True, db_column='oferta_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidad_estado_historial_por_oferta_id', to='comercial.oportunidadoferta'),
        ),
        migrations.AddField(
            model_name='oportunidadofertaproyecto',
            name='oferta',
            field=models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_declarados', to='comercial.oportunidadoferta'),
        ),
        migrations.AddField(
            model_name='oportunidadofertaproyecto',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='oportunidad_oferta_proyectos_por_proyecto_id', to='proyectos.proyecto'),
        ),
    ]
