# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConexion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_expediente', models.CharField(blank=True, max_length=100, null=True)),
                ('id_requerimiento_or', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_solicitud_appweb', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_conexion_estimada', models.DateField(blank=True, null=True)),
                ('vigencia_aprobacion_conexion', models.DateField(blank=True, null=True)),
                ('fecha_visita_protecciones', models.DateField(blank=True, null=True)),
                ('tipo_visita_protecciones', models.CharField(blank=True, max_length=20, null=True)),
                ('exporta', models.BooleanField(default=False)),
                ('comercializador_es_or', models.BooleanField(default=False)),
                ('punto_conexion_texto', models.CharField(blank=True, max_length=500, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='registro_conexion', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'registro_conexion',
            },
        ),
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('radicado', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('firmado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('url_drive', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_documento',
            },
        ),
        migrations.CreateModel(
            name='RegistroEquipoFrontera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('marca', models.CharField(blank=True, max_length=120, null=True)),
                ('modelo', models.CharField(blank=True, max_length=120, null=True)),
                ('serial', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_solicitud_solenium', models.DateField(blank=True, null=True)),
                ('fecha_envio_quoia', models.DateField(blank=True, null=True)),
                ('fecha_parametrizacion', models.DateField(blank=True, null=True)),
                ('fecha_envio_or', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_calibracion', models.DateField(blank=True, null=True)),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_equipo_frontera',
            },
        ),
        migrations.CreateModel(
            name='RegistroEtapa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=50)),
                ('estado_actual', models.CharField(max_length=50)),
                ('fecha_estado', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloqueada', models.BooleanField(default=False)),
                ('causa_bloqueo', models.CharField(blank=True, max_length=500, null=True)),
                ('responsable_actual', models.CharField(blank=True, max_length=30, null=True)),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_etapa',
                'unique_together': {('etapa', 'registro')},
            },
        ),
        migrations.CreateModel(
            name='RegistroParametros93',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_unidades_equivalentes', models.IntegerField(blank=True, null=True)),
                ('potencia_nominal_inversor_ac_mw', models.FloatField(blank=True, null=True)),
                ('minimo_tecnico_mw', models.FloatField(blank=True, null=True)),
                ('arranque_autonomo', models.BooleanField(default=False)),
                ('acuerdo_conexion_compartida', models.BooleanField(default=False)),
                ('voltaje_max_kv', models.FloatField(blank=True, null=True)),
                ('voltaje_nominal_kv', models.FloatField(blank=True, null=True)),
                ('voltaje_min_kv', models.FloatField(blank=True, null=True)),
                ('frecuencia_max_hz', models.FloatField(blank=True, default=63, null=True)),
                ('frecuencia_min_hz', models.FloatField(blank=True, default=57, null=True)),
                ('impedancia_equivalente_ohm', models.FloatField(blank=True, null=True)),
                ('icc_subtrans_pico_kap', models.FloatField(blank=True, null=True)),
                ('icc_subtrans_3f_ka', models.FloatField(blank=True, null=True)),
                ('icc_subtrans_2f_ka', models.FloatField(blank=True, null=True)),
                ('icc_subtrans_1f_ka', models.FloatField(blank=True, null=True)),
                ('icc_estado_estable_ka', models.FloatField(blank=True, null=True)),
                ('in_eq_ka', models.FloatField(blank=True, null=True)),
                ('coef_derrateo_altura', models.CharField(blank=True, max_length=120, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='parametros_93', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_parametros_93',
            },
        ),
        migrations.CreateModel(
            name='RegistroTransicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('de_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('a_estado', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.CharField(blank=True, max_length=30, null=True)),
                ('nota', models.CharField(blank=True, max_length=1000, null=True)),
                ('etapa', models.ForeignKey(db_column='etapa_id', on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='registros_cnd.registroetapa')),
                ('evidencia_documento', models.ForeignKey(blank=True, db_column='evidencia_documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_transicion_por_evidencia_documento_id', to='registros_cnd.registrodocumento')),
            ],
            options={
                'db_table': 'registro_transicion',
            },
        ),
        migrations.CreateModel(
            name='RegistroAlerta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('fecha_disparo', models.DateTimeField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_alerta',
                'unique_together': {('dedupe_key',)},
            },
        ),
        migrations.CreateModel(
            name='RegistroHito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hito', models.CharField(max_length=10)),
                ('peso_pct', models.FloatField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('evidencia_documento', models.ForeignKey(blank=True, db_column='evidencia_documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_hito_por_evidencia_documento_id', to='registros_cnd.registrodocumento')),
                ('registro', models.ForeignKey(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='registros_cnd.registroconexion')),
            ],
            options={
                'db_table': 'registro_hito',
                'unique_together': {('hito', 'registro')},
            },
        ),
    ]
